name       : celestia
version    : 1.6.1
release    : 1
source     :
    - https://celestia.space/files/celestia/1.6.1/celestia-1.6.1.zip : 5c04a7ac2c28838efebfa15f0c7734f7891eb8d60e49646bfa0258b7c0c855d2
license    : GPL-2.0-or-later
component  : office.scientific
summary    : Real-time 3D visualization of space
description: |
    A real-time space simulation that lets you experience our universe in three dimensions.
builddeps  :
    - pkgconfig(freeglut)
    - pkgconfig(gconf-2.0)
    - pkgconfig(glu)
    - pkgconfig(gtkglext-1.0)
    - pkgconfig(libturbojpeg)
    - pkgconfig(lua)
    - pkgconfig(theora)
    - pkgconfig(xmu)
setup      : |
    %apply_patches

    chmod u+x configure
    %reconfigure --with-gtk --with-lua
build      : |
    CFLAGS+=" -fsigned-char"
    CXXFLAGS+=" -fsigned-char"

    %make
install    : |
    %make_install MKDIR_P="mkdir -p"
