name       : celestia
version    : 1.6.2.2
release    : 6
source     :
    - https://github.com/CelestiaProject/Celestia/archive/refs/tags/1.6.2.2.tar.gz : d4d3bccf104a9beaf4bedb58e407172555b67113bbff3e0134d4a831d747419b
license    : GPL-2.0-or-later
component  : office.scientific
summary    : Real-time 3D visualization of space
description: |
    A real-time space simulation that lets you experience our universe in three dimensions.
builddeps  :
    - pkgconfig(gconf-2.0)
    - pkgconfig(glu)
    - pkgconfig(glut)
    - pkgconfig(gtkglext-1.0)
    - pkgconfig(libturbojpeg)
    - pkgconfig(lua)
    - pkgconfig(theora)
    - pkgconfig(xmu)
setup      : |
    %reconfigure --with-gtk --with-lua
build      : |
    CFLAGS+=" -fsigned-char"
    CXXFLAGS+=" -fsigned-char"

    %make
install    : |
    %make_install MKDIR_P="mkdir -p"
