name       : celestia
version    : 1.6.1
release    : 4
source     :
    - https://sourceforge.net/projects/celestia/files/Celestia-source/1.6.1/celestia-1.6.1.tar.gz/download : d35570ccb9440fc0bd3e73eb9b4c3e8a4c25f3ae444a13d1175053fa16dc34c4
license    : GPL-2.0-or-later
component  : office.scientific
summary    : Real-time 3D visualization of space
description: |
    A real-time space simulation that lets you experience our universe in three dimensions.
builddeps  :
    - pkgconfig(gconf-2.0)
    - pkgconfig(glu)
    - pkgconfig(glut)
    - pkgconfig(gtkglext-1.0)
    - pkgconfig(libturbojpeg)
    - pkgconfig(lua)
    - pkgconfig(theora)
    - pkgconfig(xmu)
setup      : |
    %apply_patches

    chmod u+x configure
    %reconfigure --with-gtk --with-lua
build      : |
    CFLAGS+=" -fsigned-char"
    CXXFLAGS+=" -fsigned-char"

    %make
install    : |
    %make_install MKDIR_P="mkdir -p"
